# Notebook 5: HTTP Feature Engineering

## Objective

In this notebook, we will extract behavioral features from the HTTP log of the CERT R6.2 dataset.

The HTTP dataset records every web activity performed by employees, such as:

- WWW Visit
- WWW Download
- WWW Upload

These activities help identify abnormal browsing behavior that may indicate insider threats.

---

## Features to Extract

For every employee, we will compute:

- Total HTTP events
- Total website visits
- Total downloads
- Total uploads
- After-hours HTTP activity
- Weekend HTTP activity
- Number of unique URLs visited
- Number of unique PCs used for browsing

---

## Why Chunk Processing?

The HTTP dataset contains millions of records.

Loading the entire dataset into memory causes:

- ArrowMemoryError
- MemoryError

Therefore, we process the dataset in chunks of 100,000 rows.

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path
from collections import defaultdict

# Define Dataset Paths

Here we define:

- DATA_PATH → Location of the CERT dataset
- FEATURE_PATH → Folder where extracted features will be saved

If the feature folder does not exist, it will be created automatically.

In [2]:
DATA_PATH = Path("../DATA/raw/CERT_R6.2/data")
FEATURE_PATH = Path("../DATA/features")

FEATURE_PATH.mkdir(parents=True, exist_ok=True)

# Verify Dataset

Before processing the dataset, we verify:

- Current working directory
- Whether the HTTP dataset exists

This helps avoid file path errors.

In [3]:
print("Current Working Directory:")
print(Path.cwd())

print("\nChecking HTTP Dataset...")

if (DATA_PATH / "http.csv").exists():
    print("✅ http.csv Found")
else:
    print("❌ http.csv Not Found")

Current Working Directory:
d:\OPENCODE\insider-threat-detection\NOTEBOOKS

Checking HTTP Dataset...
✅ http.csv Found

# Create Chunk Reader

Instead of loading the complete dataset into memory,
we read only 100,000 rows at a time.

This technique is called **Chunk Processing**.

Benefits:

- Very low RAM usage
- Faster processing
- Prevents ArrowMemoryError

In [4]:
chunks = pd.read_csv(
    DATA_PATH / "http.csv",
    chunksize=100000
)

print("✅ Chunk Reader Created Successfully")

✅ Chunk Reader Created Successfully

# Initialize Data Structures

We create:

- http_profiles → stores chunk-wise feature tables
- user_urls → stores unique URLs for each employee
- user_pcs → stores unique PCs used by each employee

defaultdict(set) automatically keeps only unique values.

In [5]:
http_profiles = []

user_urls = defaultdict(set)

user_pcs = defaultdict(set)

# Process Each HTTP Chunk

The HTTP dataset is too large to fit into memory.

Therefore, we process **100,000 rows at a time**.

For every chunk, we perform the following steps:

1. Convert the date column into datetime format.
2. Extract hour and weekday.
3. Detect after-hours activity.
4. Detect weekend activity.
5. Identify Visits, Downloads, and Uploads.
6. Create chunk-level user features.
7. Store unique URLs.
8. Store unique PCs.
9. Save the chunk summary.

This loop continues until the entire dataset has been processed.

In [6]:
# Process Every Chunk

for chunk_number, chunk in enumerate(chunks, start=1):

    print(f"Processing Chunk {chunk_number}")

    # --------------------------------------------------
    # Convert Date Column
    # --------------------------------------------------

    chunk["date"] = pd.to_datetime(
        chunk["date"],
        format="%m/%d/%Y %H:%M:%S"
    )

    # --------------------------------------------------
    # Extract Time Information
    # --------------------------------------------------

    chunk["hour"] = chunk["date"].dt.hour
    chunk["weekday"] = chunk["date"].dt.weekday

    # --------------------------------------------------
    # After Hours Activity
    # Working Hours : 08:00 AM - 05:59 PM
    # --------------------------------------------------

    chunk["after_hours"] = (
        (chunk["hour"] < 8) |
        (chunk["hour"] >= 18)
    ).astype(int)

    # --------------------------------------------------
    # Weekend Activity
    # Saturday = 5
    # Sunday = 6
    # --------------------------------------------------

    chunk["weekend_activity"] = (
        chunk["weekday"] >= 5
    ).astype(int)

    # --------------------------------------------------
    # HTTP Activity Types
    # --------------------------------------------------

    chunk["is_visit"] = (
        chunk["activity"] == "WWW Visit"
    ).astype(int)

    chunk["is_download"] = (
        chunk["activity"] == "WWW Download"
    ).astype(int)

    chunk["is_upload"] = (
        chunk["activity"] == "WWW Upload"
    ).astype(int)

    # --------------------------------------------------
    # Create User Features for Current Chunk
    # --------------------------------------------------

    chunk_profile = (
        chunk
        .groupby("user")
        .agg(

            total_http_events=(
                "activity",
                "count"
            ),

            http_visit_count=(
                "is_visit",
                "sum"
            ),

            http_download_count=(
                "is_download",
                "sum"
            ),

            http_upload_count=(
                "is_upload",
                "sum"
            ),

            after_hours_http_count=(
                "after_hours",
                "sum"
            ),

            weekend_http_count=(
                "weekend_activity",
                "sum"
            )

        )
        .reset_index()
    )

    # --------------------------------------------------
    # Save Chunk Features
    # --------------------------------------------------

    http_profiles.append(chunk_profile)

    # --------------------------------------------------
    # Store Unique URLs
    # --------------------------------------------------

    for user, urls in chunk.groupby("user")["url"]:

        user_urls[user].update(
            urls.dropna().unique()
        )

    # --------------------------------------------------
    # Store Unique PCs
    # --------------------------------------------------

    for user, pcs in chunk.groupby("user")["pc"]:

        user_pcs[user].update(
            pcs.dropna().unique()
        )

print("\n✅ All Chunks Processed Successfully")

Processing Chunk 1
Processing Chunk 2
Processing Chunk 3
Processing Chunk 4
Processing Chunk 5
Processing Chunk 6
Processing Chunk 7
Processing Chunk 8
Processing Chunk 9
Processing Chunk 10
Processing Chunk 11
Processing Chunk 12
Processing Chunk 13
Processing Chunk 14
Processing Chunk 15
Processing Chunk 16
Processing Chunk 17
Processing Chunk 18
Processing Chunk 19
Processing Chunk 20
Processing Chunk 21
Processing Chunk 22
Processing Chunk 23
Processing Chunk 24
Processing Chunk 25
Processing Chunk 26
Processing Chunk 27
Processing Chunk 28
Processing Chunk 29
Processing Chunk 30
Processing Chunk 31
Processing Chunk 32
Processing Chunk 33
Processing Chunk 34
Processing Chunk 35
Processing Chunk 36
Processing Chunk 37
Processing Chunk 38
Processing Chunk 39
Processing Chunk 40
Processing Chunk 41
Processing Chunk 42
Processing Chunk 43
Processing Chunk 44
Processing Chunk 45
Processing Chunk 46
Processing Chunk 47
Processing Chunk 48
Processing Chunk 49
Processing Chunk 50
Processing Chunk 51
Processing Chunk 52
Processing Chunk 53
Processing Chunk 54
Processing Chunk 55
Processing Chunk 56
Processing Chunk 57
Processing Chunk 58
Processing Chunk 59
Processing Chunk 60
Processing Chunk 61
Processing Chunk 62
Processing Chunk 63
Processing Chunk 64
Processing Chunk 65
Processing Chunk 66
Processing Chunk 67
Processing Chunk 68
Processing Chunk 69
Processing Chunk 70
Processing Chunk 71
Processing Chunk 72
Processing Chunk 73
Processing Chunk 74
Processing Chunk 75
Processing Chunk 76
Processing Chunk 77
Processing Chunk 78
Processing Chunk 79
Processing Chunk 80
Processing Chunk 81
Processing Chunk 82
Processing Chunk 83
Processing Chunk 84
Processing Chunk 85
Processing Chunk 86
Processing Chunk 87
Processing Chunk 88
Processing Chunk 89
Processing Chunk 90
Processing Chunk 91
Processing Chunk 92
Processing Chunk 93
Processing Chunk 94
Processing Chunk 95
Processing Chunk 96
Processing Chunk 97
Processing Chunk 98
Processing Chunk 99
Processing Chunk 100
Processing Chunk 101
Processing Chunk 102
Processing Chunk 103
Processing Chunk 104
Processing Chunk 105
Processing Chunk 106
Processing Chunk 107
Processing Chunk 108
Processing Chunk 109
Processing Chunk 110
Processing Chunk 111
Processing Chunk 112
Processing Chunk 113
Processing Chunk 114
Processing Chunk 115
Processing Chunk 116
Processing Chunk 117
Processing Chunk 118
Processing Chunk 119
Processing Chunk 120
Processing Chunk 121
Processing Chunk 122
Processing Chunk 123
Processing Chunk 124
Processing Chunk 125
Processing Chunk 126
Processing Chunk 127
Processing Chunk 128
Processing Chunk 129
Processing Chunk 130
Processing Chunk 131
Processing Chunk 132
Processing Chunk 133
Processing Chunk 134
Processing Chunk 135
Processing Chunk 136
Processing Chunk 137
Processing Chunk 138
Processing Chunk 139
Processing Chunk 140
Processing Chunk 141
Processing Chunk 142
Processing Chunk 143
Processing Chunk 144
Processing Chunk 145
Processing Chunk 146
Processing Chunk 147
Processing Chunk 148
Processing Chunk 149
Processing Chunk 150
Processing Chunk 151
Processing Chunk 152
Processing Chunk 153
Processing Chunk 154
Processing Chunk 155
Processing Chunk 156
Processing Chunk 157
Processing Chunk 158
Processing Chunk 159
Processing Chunk 160
Processing Chunk 161
Processing Chunk 162
Processing Chunk 163
Processing Chunk 164
Processing Chunk 165
Processing Chunk 166
Processing Chunk 167
Processing Chunk 168
Processing Chunk 169
Processing Chunk 170
Processing Chunk 171
Processing Chunk 172
Processing Chunk 173
Processing Chunk 174
Processing Chunk 175
Processing Chunk 176
Processing Chunk 177
Processing Chunk 178
Processing Chunk 179
Processing Chunk 180
Processing Chunk 181
Processing Chunk 182
Processing Chunk 183
Processing Chunk 184
Processing Chunk 185
Processing Chunk 186
Processing Chunk 187
Processing Chunk 188
Processing Chunk 189
Processing Chunk 190
Processing Chunk 191
Processing Chunk 192
Processing Chunk 193
Processing Chunk 194
Processing Chunk 195
Processing Chunk 196
Processing Chunk 197
Processing Chunk 198
Processing Chunk 199
Processing Chunk 200
Processing Chunk 201
Processing Chunk 202
Processing Chunk 203
Processing Chunk 204
Processing Chunk 205
Processing Chunk 206
Processing Chunk 207
Processing Chunk 208
Processing Chunk 209
Processing Chunk 210
Processing Chunk 211
Processing Chunk 212
Processing Chunk 213
Processing Chunk 214
Processing Chunk 215
Processing Chunk 216
Processing Chunk 217
Processing Chunk 218
Processing Chunk 219
Processing Chunk 220
Processing Chunk 221
Processing Chunk 222
Processing Chunk 223
Processing Chunk 224
Processing Chunk 225
Processing Chunk 226
Processing Chunk 227
Processing Chunk 228
Processing Chunk 229
Processing Chunk 230
Processing Chunk 231
Processing Chunk 232
Processing Chunk 233
Processing Chunk 234
Processing Chunk 235
Processing Chunk 236
Processing Chunk 237
Processing Chunk 238
Processing Chunk 239
Processing Chunk 240
Processing Chunk 241
Processing Chunk 242
Processing Chunk 243
Processing Chunk 244
Processing Chunk 245
Processing Chunk 246
Processing Chunk 247
Processing Chunk 248
Processing Chunk 249
Processing Chunk 250
Processing Chunk 251
Processing Chunk 252
Processing Chunk 253
Processing Chunk 254
Processing Chunk 255
Processing Chunk 256
Processing Chunk 257
Processing Chunk 258
Processing Chunk 259
Processing Chunk 260
Processing Chunk 261
Processing Chunk 262
Processing Chunk 263
Processing Chunk 264
Processing Chunk 265
Processing Chunk 266
Processing Chunk 267
Processing Chunk 268
Processing Chunk 269
Processing Chunk 270
Processing Chunk 271
Processing Chunk 272
Processing Chunk 273
Processing Chunk 274
Processing Chunk 275
Processing Chunk 276
Processing Chunk 277
Processing Chunk 278
Processing Chunk 279
Processing Chunk 280
Processing Chunk 281
Processing Chunk 282
Processing Chunk 283
Processing Chunk 284
Processing Chunk 285
Processing Chunk 286
Processing Chunk 287
Processing Chunk 288
Processing Chunk 289
Processing Chunk 290
Processing Chunk 291
Processing Chunk 292
Processing Chunk 293
Processing Chunk 294
Processing Chunk 295
Processing Chunk 296
Processing Chunk 297
Processing Chunk 298
Processing Chunk 299
Processing Chunk 300
Processing Chunk 301
Processing Chunk 302
Processing Chunk 303
Processing Chunk 304
Processing Chunk 305
Processing Chunk 306
Processing Chunk 307
Processing Chunk 308
Processing Chunk 309
Processing Chunk 310
Processing Chunk 311
Processing Chunk 312
Processing Chunk 313
Processing Chunk 314
Processing Chunk 315
Processing Chunk 316
Processing Chunk 317
Processing Chunk 318
Processing Chunk 319
Processing Chunk 320
Processing Chunk 321
Processing Chunk 322
Processing Chunk 323
Processing Chunk 324
Processing Chunk 325
Processing Chunk 326
Processing Chunk 327
Processing Chunk 328
Processing Chunk 329
Processing Chunk 330
Processing Chunk 331
Processing Chunk 332
Processing Chunk 333
Processing Chunk 334
Processing Chunk 335
Processing Chunk 336
Processing Chunk 337
Processing Chunk 338
Processing Chunk 339
Processing Chunk 340
Processing Chunk 341
Processing Chunk 342
Processing Chunk 343
Processing Chunk 344
Processing Chunk 345
Processing Chunk 346
Processing Chunk 347
Processing Chunk 348
Processing Chunk 349
Processing Chunk 350
Processing Chunk 351
Processing Chunk 352
Processing Chunk 353
Processing Chunk 354
Processing Chunk 355
Processing Chunk 356
Processing Chunk 357
Processing Chunk 358
Processing Chunk 359
Processing Chunk 360
Processing Chunk 361
Processing Chunk 362
Processing Chunk 363
Processing Chunk 364
Processing Chunk 365
Processing Chunk 366
Processing Chunk 367
Processing Chunk 368
Processing Chunk 369
Processing Chunk 370
Processing Chunk 371
Processing Chunk 372
Processing Chunk 373
Processing Chunk 374
Processing Chunk 375
Processing Chunk 376
Processing Chunk 377
Processing Chunk 378
Processing Chunk 379
Processing Chunk 380
Processing Chunk 381
Processing Chunk 382
Processing Chunk 383
Processing Chunk 384
Processing Chunk 385
Processing Chunk 386
Processing Chunk 387
Processing Chunk 388
Processing Chunk 389
Processing Chunk 390
Processing Chunk 391
Processing Chunk 392
Processing Chunk 393
Processing Chunk 394
Processing Chunk 395
Processing Chunk 396
Processing Chunk 397
Processing Chunk 398
Processing Chunk 399
Processing Chunk 400
Processing Chunk 401
Processing Chunk 402
Processing Chunk 403
Processing Chunk 404
Processing Chunk 405
Processing Chunk 406
Processing Chunk 407
Processing Chunk 408
Processing Chunk 409
Processing Chunk 410
Processing Chunk 411
Processing Chunk 412
Processing Chunk 413
Processing Chunk 414
Processing Chunk 415
Processing Chunk 416
Processing Chunk 417
Processing Chunk 418
Processing Chunk 419
Processing Chunk 420
Processing Chunk 421
Processing Chunk 422
Processing Chunk 423
Processing Chunk 424
Processing Chunk 425
Processing Chunk 426
Processing Chunk 427
Processing Chunk 428
Processing Chunk 429
Processing Chunk 430
Processing Chunk 431
Processing Chunk 432
Processing Chunk 433
Processing Chunk 434
Processing Chunk 435
Processing Chunk 436
Processing Chunk 437
Processing Chunk 438
Processing Chunk 439
Processing Chunk 440
Processing Chunk 441
Processing Chunk 442
Processing Chunk 443
Processing Chunk 444
Processing Chunk 445
Processing Chunk 446
Processing Chunk 447
Processing Chunk 448
Processing Chunk 449
Processing Chunk 450
Processing Chunk 451
Processing Chunk 452
Processing Chunk 453
Processing Chunk 454
Processing Chunk 455
Processing Chunk 456
Processing Chunk 457
Processing Chunk 458
Processing Chunk 459
Processing Chunk 460
Processing Chunk 461
Processing Chunk 462
Processing Chunk 463
Processing Chunk 464
Processing Chunk 465
Processing Chunk 466
Processing Chunk 467
Processing Chunk 468
Processing Chunk 469
Processing Chunk 470
Processing Chunk 471
Processing Chunk 472
Processing Chunk 473
Processing Chunk 474
Processing Chunk 475
Processing Chunk 476
Processing Chunk 477
Processing Chunk 478
Processing Chunk 479
Processing Chunk 480
Processing Chunk 481
Processing Chunk 482
Processing Chunk 483
Processing Chunk 484
Processing Chunk 485
Processing Chunk 486
Processing Chunk 487
Processing Chunk 488
Processing Chunk 489
Processing Chunk 490
Processing Chunk 491
Processing Chunk 492
Processing Chunk 493
Processing Chunk 494
Processing Chunk 495
Processing Chunk 496
Processing Chunk 497
Processing Chunk 498
Processing Chunk 499
Processing Chunk 500
Processing Chunk 501
Processing Chunk 502
Processing Chunk 503
Processing Chunk 504
Processing Chunk 505
Processing Chunk 506
Processing Chunk 507
Processing Chunk 508
Processing Chunk 509
Processing Chunk 510
Processing Chunk 511
Processing Chunk 512
Processing Chunk 513
Processing Chunk 514
Processing Chunk 515
Processing Chunk 516
Processing Chunk 517
Processing Chunk 518
Processing Chunk 519
Processing Chunk 520
Processing Chunk 521
Processing Chunk 522
Processing Chunk 523
Processing Chunk 524
Processing Chunk 525
Processing Chunk 526
Processing Chunk 527
Processing Chunk 528
Processing Chunk 529
Processing Chunk 530
Processing Chunk 531
Processing Chunk 532
Processing Chunk 533
Processing Chunk 534
Processing Chunk 535
Processing Chunk 536
Processing Chunk 537
Processing Chunk 538
Processing Chunk 539
Processing Chunk 540
Processing Chunk 541
Processing Chunk 542
Processing Chunk 543
Processing Chunk 544
Processing Chunk 545
Processing Chunk 546
Processing Chunk 547
Processing Chunk 548
Processing Chunk 549
Processing Chunk 550
Processing Chunk 551
Processing Chunk 552
Processing Chunk 553
Processing Chunk 554
Processing Chunk 555
Processing Chunk 556
Processing Chunk 557
Processing Chunk 558
Processing Chunk 559
Processing Chunk 560
Processing Chunk 561
Processing Chunk 562
Processing Chunk 563
Processing Chunk 564
Processing Chunk 565
Processing Chunk 566
Processing Chunk 567
Processing Chunk 568
Processing Chunk 569
Processing Chunk 570
Processing Chunk 571
Processing Chunk 572
Processing Chunk 573
Processing Chunk 574
Processing Chunk 575
Processing Chunk 576
Processing Chunk 577
Processing Chunk 578
Processing Chunk 579
Processing Chunk 580
Processing Chunk 581
Processing Chunk 582
Processing Chunk 583
Processing Chunk 584
Processing Chunk 585
Processing Chunk 586
Processing Chunk 587
Processing Chunk 588
Processing Chunk 589
Processing Chunk 590
Processing Chunk 591
Processing Chunk 592
Processing Chunk 593
Processing Chunk 594
Processing Chunk 595
Processing Chunk 596
Processing Chunk 597
Processing Chunk 598
Processing Chunk 599
Processing Chunk 600
Processing Chunk 601
Processing Chunk 602
Processing Chunk 603
Processing Chunk 604
Processing Chunk 605
Processing Chunk 606
Processing Chunk 607
Processing Chunk 608
Processing Chunk 609
Processing Chunk 610
Processing Chunk 611
Processing Chunk 612
Processing Chunk 613
Processing Chunk 614
Processing Chunk 615
Processing Chunk 616
Processing Chunk 617
Processing Chunk 618
Processing Chunk 619
Processing Chunk 620
Processing Chunk 621
Processing Chunk 622
Processing Chunk 623
Processing Chunk 624
Processing Chunk 625
Processing Chunk 626
Processing Chunk 627
Processing Chunk 628
Processing Chunk 629
Processing Chunk 630
Processing Chunk 631
Processing Chunk 632
Processing Chunk 633
Processing Chunk 634
Processing Chunk 635
Processing Chunk 636
Processing Chunk 637
Processing Chunk 638
Processing Chunk 639
Processing Chunk 640
Processing Chunk 641
Processing Chunk 642
Processing Chunk 643
Processing Chunk 644
Processing Chunk 645
Processing Chunk 646
Processing Chunk 647
Processing Chunk 648
Processing Chunk 649
Processing Chunk 650
Processing Chunk 651
Processing Chunk 652
Processing Chunk 653
Processing Chunk 654
Processing Chunk 655
Processing Chunk 656
Processing Chunk 657
Processing Chunk 658
Processing Chunk 659
Processing Chunk 660
Processing Chunk 661
Processing Chunk 662
Processing Chunk 663
Processing Chunk 664
Processing Chunk 665
Processing Chunk 666
Processing Chunk 667
Processing Chunk 668
Processing Chunk 669
Processing Chunk 670
Processing Chunk 671
Processing Chunk 672
Processing Chunk 673
Processing Chunk 674
Processing Chunk 675
Processing Chunk 676
Processing Chunk 677
Processing Chunk 678
Processing Chunk 679
Processing Chunk 680
Processing Chunk 681
Processing Chunk 682
Processing Chunk 683
Processing Chunk 684
Processing Chunk 685
Processing Chunk 686
Processing Chunk 687
Processing Chunk 688
Processing Chunk 689
Processing Chunk 690
Processing Chunk 691
Processing Chunk 692
Processing Chunk 693
Processing Chunk 694
Processing Chunk 695
Processing Chunk 696
Processing Chunk 697
Processing Chunk 698
Processing Chunk 699
Processing Chunk 700
Processing Chunk 701
Processing Chunk 702
Processing Chunk 703
Processing Chunk 704
Processing Chunk 705
Processing Chunk 706
Processing Chunk 707
Processing Chunk 708
Processing Chunk 709
Processing Chunk 710
Processing Chunk 711
Processing Chunk 712
Processing Chunk 713
Processing Chunk 714
Processing Chunk 715
Processing Chunk 716
Processing Chunk 717
Processing Chunk 718
Processing Chunk 719
Processing Chunk 720
Processing Chunk 721
Processing Chunk 722
Processing Chunk 723
Processing Chunk 724
Processing Chunk 725
Processing Chunk 726
Processing Chunk 727
Processing Chunk 728
Processing Chunk 729
Processing Chunk 730
Processing Chunk 731
Processing Chunk 732
Processing Chunk 733
Processing Chunk 734
Processing Chunk 735
Processing Chunk 736
Processing Chunk 737
Processing Chunk 738
Processing Chunk 739
Processing Chunk 740
Processing Chunk 741
Processing Chunk 742
Processing Chunk 743
Processing Chunk 744
Processing Chunk 745
Processing Chunk 746
Processing Chunk 747
Processing Chunk 748
Processing Chunk 749
Processing Chunk 750
Processing Chunk 751
Processing Chunk 752
Processing Chunk 753
Processing Chunk 754
Processing Chunk 755
Processing Chunk 756
Processing Chunk 757
Processing Chunk 758
Processing Chunk 759
Processing Chunk 760
Processing Chunk 761
Processing Chunk 762
Processing Chunk 763
Processing Chunk 764
Processing Chunk 765
Processing Chunk 766
Processing Chunk 767
Processing Chunk 768
Processing Chunk 769
Processing Chunk 770
Processing Chunk 771
Processing Chunk 772
Processing Chunk 773
Processing Chunk 774
Processing Chunk 775
Processing Chunk 776
Processing Chunk 777
Processing Chunk 778
Processing Chunk 779
Processing Chunk 780
Processing Chunk 781
Processing Chunk 782
Processing Chunk 783
Processing Chunk 784
Processing Chunk 785
Processing Chunk 786
Processing Chunk 787
Processing Chunk 788
Processing Chunk 789
Processing Chunk 790
Processing Chunk 791
Processing Chunk 792
Processing Chunk 793
Processing Chunk 794
Processing Chunk 795
Processing Chunk 796
Processing Chunk 797
Processing Chunk 798
Processing Chunk 799
Processing Chunk 800
Processing Chunk 801
Processing Chunk 802
Processing Chunk 803
Processing Chunk 804
Processing Chunk 805
Processing Chunk 806
Processing Chunk 807
Processing Chunk 808
Processing Chunk 809
Processing Chunk 810
Processing Chunk 811
Processing Chunk 812
Processing Chunk 813
Processing Chunk 814
Processing Chunk 815
Processing Chunk 816
Processing Chunk 817
Processing Chunk 818
Processing Chunk 819
Processing Chunk 820
Processing Chunk 821
Processing Chunk 822
Processing Chunk 823
Processing Chunk 824
Processing Chunk 825
Processing Chunk 826
Processing Chunk 827
Processing Chunk 828
Processing Chunk 829
Processing Chunk 830
Processing Chunk 831
Processing Chunk 832
Processing Chunk 833
Processing Chunk 834
Processing Chunk 835
Processing Chunk 836
Processing Chunk 837
Processing Chunk 838
Processing Chunk 839
Processing Chunk 840
Processing Chunk 841
Processing Chunk 842
Processing Chunk 843
Processing Chunk 844
Processing Chunk 845
Processing Chunk 846
Processing Chunk 847
Processing Chunk 848
Processing Chunk 849
Processing Chunk 850
Processing Chunk 851
Processing Chunk 852
Processing Chunk 853
Processing Chunk 854
Processing Chunk 855
Processing Chunk 856
Processing Chunk 857
Processing Chunk 858
Processing Chunk 859
Processing Chunk 860
Processing Chunk 861
Processing Chunk 862
Processing Chunk 863
Processing Chunk 864
Processing Chunk 865
Processing Chunk 866
Processing Chunk 867
Processing Chunk 868
Processing Chunk 869
Processing Chunk 870
Processing Chunk 871
Processing Chunk 872
Processing Chunk 873
Processing Chunk 874
Processing Chunk 875
Processing Chunk 876
Processing Chunk 877
Processing Chunk 878
Processing Chunk 879
Processing Chunk 880
Processing Chunk 881
Processing Chunk 882
Processing Chunk 883
Processing Chunk 884
Processing Chunk 885
Processing Chunk 886
Processing Chunk 887
Processing Chunk 888
Processing Chunk 889
Processing Chunk 890
Processing Chunk 891
Processing Chunk 892
Processing Chunk 893
Processing Chunk 894
Processing Chunk 895
Processing Chunk 896
Processing Chunk 897
Processing Chunk 898
Processing Chunk 899
Processing Chunk 900
Processing Chunk 901
Processing Chunk 902
Processing Chunk 903
Processing Chunk 904
Processing Chunk 905
Processing Chunk 906
Processing Chunk 907
Processing Chunk 908
Processing Chunk 909
Processing Chunk 910
Processing Chunk 911
Processing Chunk 912
Processing Chunk 913
Processing Chunk 914
Processing Chunk 915
Processing Chunk 916
Processing Chunk 917
Processing Chunk 918
Processing Chunk 919
Processing Chunk 920
Processing Chunk 921
Processing Chunk 922
Processing Chunk 923
Processing Chunk 924
Processing Chunk 925
Processing Chunk 926
Processing Chunk 927
Processing Chunk 928
Processing Chunk 929
Processing Chunk 930
Processing Chunk 931
Processing Chunk 932
Processing Chunk 933
Processing Chunk 934
Processing Chunk 935
Processing Chunk 936
Processing Chunk 937
Processing Chunk 938
Processing Chunk 939
Processing Chunk 940
Processing Chunk 941
Processing Chunk 942
Processing Chunk 943
Processing Chunk 944
Processing Chunk 945
Processing Chunk 946
Processing Chunk 947
Processing Chunk 948
Processing Chunk 949
Processing Chunk 950
Processing Chunk 951
Processing Chunk 952
Processing Chunk 953
Processing Chunk 954
Processing Chunk 955
Processing Chunk 956
Processing Chunk 957

# Merge Chunk Features

Each chunk contains user-level HTTP features.

Since the same user can appear in multiple chunks, we need to:

1. Combine all chunk summaries.
2. Merge duplicate users.
3. Sum all feature values.

This produces one final row for each user.

In [7]:
# Combine All Chunk Profiles

http_profile = pd.concat(
    http_profiles,
    ignore_index=True
)

print("Rows Before User Merge:", len(http_profile))

http_profile.head()

Rows Before User Merge: 4420795

,user,total_http_events,http_visit_count,http_download_count,http_upload_count,after_hours_http_count,weekend_http_count
0,AAB0162,30,30,0,0,3,0
1,AAB0398,21,21,0,0,5,0
2,AAC0610,7,7,0,0,1,0
3,AAC0668,15,15,0,0,1,0
4,AAC3270,2,2,0,0,0,0

# Aggregate Duplicate Users

The same employee may appear in multiple chunks.

We group by the user column and sum all numerical features to obtain one final record per employee.

In [8]:
http_profile = (
    http_profile
    .groupby("user", as_index=False)
    .sum(numeric_only=True)
)

print("Unique Users:", len(http_profile))

http_profile.head()

Unique Users: 4000

,user,total_http_events,http_visit_count,http_download_count,http_upload_count,after_hours_http_count,weekend_http_count
0,AAB0162,33725,33725,0,0,4277,0
1,AAB0398,40584,40584,0,0,7128,0
2,AAC0610,10324,10324,0,0,240,0
3,AAC0668,33820,33820,0,0,320,0
4,AAC3270,3560,3560,0,0,0,0

# Calculate Unique URLs

During chunk processing, we stored every unique URL visited by each employee.

Now we calculate the total number of unique URLs for every user.

In [9]:
unique_url_df = pd.DataFrame({

    "user": list(user_urls.keys()),

    "unique_urls": [
        len(urls)
        for urls in user_urls.values()
    ]

})

print("Unique URL Features")

unique_url_df.head()

Unique URL Features

      user  unique_urls
0  AAB0162          144
1  AAB0398          351
2  AAC0610          267
3  AAC0668          227
4  AAC3270           60

# Calculate Unique PCs

Similarly, we calculate how many different computers each employee used while accessing websites.

In [10]:
unique_pc_df = pd.DataFrame({

    "user": list(user_pcs.keys()),

    "unique_http_pcs": [
        len(pcs)
        for pcs in user_pcs.values()
    ]

})

print("Unique PC Features")

unique_pc_df.head()

Unique PC Features

      user  unique_http_pcs
0  AAB0162                1
1  AAB0398                1
2  AAC0610                1
3  AAC0668                1
4  AAC3270                1

# Merge All HTTP Features

Now we combine:

- Chunk-based HTTP statistics
- Unique URL counts
- Unique PC counts

This creates the final HTTP feature table.

In [11]:
# Merge URL Features

http_profile = http_profile.merge(

    unique_url_df,

    on="user",

    how="left"

)

# Merge PC Features

http_profile = http_profile.merge(

    unique_pc_df,

    on="user",

    how="left"

)

# Replace Missing Values

http_profile = http_profile.fillna(0)

print("Missing Values")

print(http_profile.isnull().sum())

Missing Values
user                      0
total_http_events         0
http_visit_count          0
http_download_count       0
http_upload_count         0
after_hours_http_count    0
weekend_http_count        0
unique_urls               0
unique_http_pcs           0
dtype: int64

# Verify Final Dataset

Let's inspect the final dataset before saving it.

We verify:

- Number of rows
- Number of columns
- Data types
- Sample records

In [12]:
print("Final Dataset Shape:")

print(http_profile.shape)

print("\nDataset Information")

http_profile.info()

print("\nFirst Five Rows")

http_profile.head()

Final Dataset Shape:
(4000, 9)

Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user                    4000 non-null   str
 1   total_http_events       4000 non-null   int64
 2   http_visit_count        4000 non-null   int64
 3   http_download_count     4000 non-null   int64
 4   http_upload_count       4000 non-null   int64
 5   after_hours_http_count  4000 non-null   int64
 6   weekend_http_count      4000 non-null   int64
 7   unique_urls             4000 non-null   int64
 8   unique_http_pcs         4000 non-null   int64
dtypes: int64(8), str(1)
memory usage: 309.2 KB

First Five Rows

,user,total_http_events,http_visit_count,http_download_count,http_upload_count,after_hours_http_count,weekend_http_count,unique_urls,unique_http_pcs
0,AAB0162,33725,33725,0,0,4277,0,144,1
1,AAB0398,40584,40584,0,0,7128,0,351,1
2,AAC0610,10324,10324,0,0,240,0,267,1
3,AAC0668,33820,33820,0,0,320,0,227,1
4,AAC3270,3560,3560,0,0,0,0,60,1

# Save HTTP Features

The final HTTP feature dataset is saved inside the `features` folder.

This dataset will be used later when combining features from:

- Logon
- Device
- Email
- File
- Psychometric
- LDAP

to build the complete Insider Threat Detection dataset.

In [13]:
output_file = FEATURE_PATH / "http_features.csv"

http_profile.to_csv(

    output_file,

    index=False

)

print(f"✅ HTTP Features Saved Successfully!")

print(f"Location: {output_file}")

✅ HTTP Features Saved Successfully!
Location: ..\DATA\features\http_features.csv

# Verify Saved File

Finally, we reload the saved file to ensure it has been written correctly.

This is a good practice before moving to the next notebook.

In [14]:
saved_http = pd.read_csv(output_file)

print("Saved Dataset Shape:")

print(saved_http.shape)

saved_http.head()

Saved Dataset Shape:
(4000, 9)

,user,total_http_events,http_visit_count,http_download_count,http_upload_count,after_hours_http_count,weekend_http_count,unique_urls,unique_http_pcs
0,AAB0162,33725,33725,0,0,4277,0,144,1
1,AAB0398,40584,40584,0,0,7128,0,351,1
2,AAC0610,10324,10324,0,0,240,0,267,1
3,AAC0668,33820,33820,0,0,320,0,227,1
4,AAC3270,3560,3560,0,0,0,0,60,1